name: Test

on:
  push:
    branches:
      - "**"

jobs:
  cluster-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
      - uses: opsgang/ga-setup-minikube@v0.1.1
        with:
          minikube-version: 1.4.0
          k8s-version: 1.15.1

      - name: Cluster Start
        run: |
          minikube config set vm-driver kvm2
          minikube config set kubernetes-version v1.15.1
          minikube start
          minikube update-context

      - name: Go Test
        id: test
        run: cd test && go test
