name: Test

on:
  push:
    branches:
      - "**"

jobs:
  cluster-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
      - uses: manusa/actions-setup-minikube@v1.0.2
        with:
          minikube version: 'v1.9.2'
          kubernetes version: 'v1.18.2'

      - name: Go Test
        id: test
        run: cd test && go test
