name: Verify

on:
  push:
    branches:
      - "**"

jobs:
  pipeline:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
      - uses: hashicorp/setup-terraform@v1

      - name: Terraform fmt
        id: tf-fmt
        run: terraform fmt -check -recursive

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color

      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color

      - name: Go fmt
        id: go-fmt
        run: cd test && go fmt
