name: Verify

on:
  push:
    branches:
      - "**"

jobs:
  tf-checks:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: hashicorp/setup-terraform@v1

      - name: Terraform fmt
        id: tf-fmt
        run: terraform fmt -check -recursive

      - name: Terraform Docs
        uses: Dirrk/terraform-docs@v1.0.8
        with:
          tf_docs_working_dir: .
          tf_docs_output_file: README.md
          tf_docs_output_method: inject
          tf_docs_git_push: 'true'

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color

      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color

  go-checks:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2

      - name: Go fmt
        id: go-fmt
        run: cd test && go fmt
